import hackathonImg from "../../../../../assets/premium_hackathon_trophy.png";
import hackathonimg2 from "../../../../../assets/Hackathon_2.jpg";
import bootcampImg from "../../../../../assets/bootcamp_3d_illustration.png";
import workshopImg from "../../../../../assets/workshop_lightbulb_idea.png";
export const events = [
  {
    id: 1,
    type: "hackathon",
    mode: "offline",
    img: hackathonImg,
    badge: "HACKATHON",
    date: "Oct 24-26, 2026",
    title: "AI Innovation Hackathon 2026",
    desc: "48-hour hackathon to build AI solutions for real-world problems. Mentors from top tech companies.",
    meta: "📍 Hyderabad • Offline",
    s1: "₹2L Prize",
    s2: "450+ Joined",
    btn: "Register Now",
    viewBtn: "View Details",
    theme: "Artificial Intelligence & Innovation",
    duration: "48 Hours",
    venue: "Hyderabad, Telangana",
    deadline: "October 20, 2026",
    organizer: "Tech Innovation Foundation",
  },
  {
    id: 2,
    type: "hackathon",
    mode: "online",
    img: hackathonimg2,
    badge: "HACKATHON",
    date: "Nov 10-12, 2026",
    title: "Web3 Build Hackathon",
    desc: "Build decentralized apps on Polygon. Grants and hiring opportunities for winners.",
    meta: "🌐 Remote • Global",
    s1: "₹1.5L Grants",
    s2: "200+ Teams",
    btn: "Register Now",
    viewBtn: "View Details",
    theme: "Web3 & Blockchain",
    duration: "48 Hours",
    venue: "Online • Global",
    deadline: "November 5, 2026",
    organizer: "Web3 Innovation Community",
  },
  {
    id: 3,
    type: "bootcamp",
    mode: "online",
    img: bootcampImg,
    badge: "BOOTCAMP",
    date: "14 Days",
    title: "Full Stack Bootcamp - MERN",
    desc: "Intensive 14-day bootcamp. Build 3 production apps and deploy them live.",
    meta: "🎓 Beginner to Advanced • Online",
    s1: "Certificate",
    s2: "Live Mentor",
    btn: "Enroll Now",
    viewBtn: "View Details",
    theme: "MERN Full Stack Development",
    duration: "14 Days",
    venue: "Online Live Classes",
    deadline: "September 30, 2026",
    organizer: "Tech Learning Academy",
  },
  {
    id: 4,
    type: "bootcamp",
    mode: "online",
    img: bootcampImg,
    badge: "BOOTCAMP",
    date: "21 Days",
    title: "AI / ML Bootcamp",
    desc: "From Python to LLMs. Build your own AI models and deploy them.",
    meta: "🧠 Intermediate • Online",
    s1: "Capstone Project",
    s2: "Job Assist",
    btn: "Enroll Now",
    viewBtn: "View Details",
    theme: "Artificial Intelligence & Machine Learning",
    duration: "21 Days",
    venue: "Online Live Classes",
    deadline: "October 10, 2026",
    organizer: "AI Learning Academy",
  },
  {
    id: 5,
    type: "workshop",
    mode: "offline",
    img: workshopImg,
    badge: "WORKSHOP",
    date: "Sep 28, 2026",
    title: "System Design Workshop",
    desc: "Learn how to design scalable systems like Netflix & Instagram with industry experts.",
    meta: "👨‍🏫 Hyderabad • Offline",
    s1: "32 Seats Left",
    s2: "2 Hours Live",
    btn: "Join Workshop",
    viewBtn: "View Details",
    theme: "System Design & Scalable Architecture",
    duration: "2 Hours",
    venue: "Hyderabad, Telangana",
    deadline: "September 27, 2026",
    organizer: "Tech Skills Academy",
  },
  {
    id: 6,
    type: "workshop",
    mode: "online",
    img: workshopImg,
    badge: "WORKSHOP",
    date: "Oct 02, 2026",
    title: "Resume & LinkedIn Mastery",
    desc: "Learn how to build a strong resume and LinkedIn profile that gets shortlisted.",
    meta: "💼 Online • Live",
    s1: "Free Workshop",
    s2: "1.5 Hours",
    btn: "Reserve Seat",
    viewBtn: "View Details",
    theme: "Career Development & Personal Branding",
    duration: "1.5 Hours",
    venue: "Online Live Session",
    deadline: "October 1, 2026",
    organizer: "Career Growth Academy",
  },
  {
    id: 7,
    type: "industrial",
    mode: "online",
    img: bootcampImg,
    badge: "INDUSTRIAL TRAINING",
    date: "30 Days",
    title: "Full Stack Industrial Training",
    desc: "Industry-focused training with real-time projects, coding practice and mentor guidance.",
    meta: "🌐 Online • Live Mentor",
    s1: "Live Projects",
    s2: "Certificate",
    btn: "Apply Now",
    viewBtn: "View Details",
    theme: "Full Stack Web Development",
    duration: "30 Days",
    venue: "Online Live Training",
    deadline: "October 15, 2026",
    organizer: "Industry Training Hub",
  },
  {
    id: 8,
    type: "industrial",
    mode: "offline",
    img: workshopImg,
    badge: "INDUSTRIAL TRAINING",
    date: "45 Days",
    title: "AI & Data Science Industrial Training",
    desc: "Hands-on industrial training covering Python, machine learning, data analysis and projects.",
    meta: "🏢 Hyderabad • Offline",
    s1: "Real Projects",
    s2: "Mentor Support",
    btn: "Apply Now",
    viewBtn: "View Details",
    theme: "AI, Machine Learning & Data Science",
    duration: "45 Days",
    venue: "Hyderabad, Telangana",
    deadline: "October 25, 2026",
    organizer: "Data Science Training Institute",
  },
];